### PR TITLE
Added gamepad instructions to README

### PR DESCRIPTION
**Pull request by troy0820**
- Added gamepad instructions to README
- Added image of the gamepad controller
- Added logitech image disclaimer

### CODE REVIEW

**Comment by lynnaloo** [comment]
@dlindahl has some changes too. Do you two want to collaborate or should I pull this in and merge conflicts?

**Comment by troy0820** [comment]
I pulled in his changes, then made some other changes. I left the branch there but I did merge it into master

**Comment by lynnaloo** [comment]
Can you move `gamepad` to `optionalDependencies` so that the install doesn't fail if they're on Node 6? Then they're just limited to keyboard controls.

**Comment by troy0820** [comment]
Yeah that'll work, I'll commit it to this branch.

**Comment by troy0820** [comment]
@lynnaloo I changed it 👍

**Pull request merged**
